export const ADD_BUDGET_LIMIT_REQUEST = "ADD_BUDGET_LIMIT_REQUEST";
export const ADD_BUDGET_LIMIT_SUCCESS = "ADD_BUDGET_LIMIT_SUCCESS";
export const ADD_BUDGET_LIMIT_FAIL = "ADD_BUDGET_LIMIT_FAIL";

export const UPDATE_BUDGET_LIMIT_REQUEST = "UPDATE_BUDGET_LIMIT_REQUEST";
export const UPDATE_BUDGET_LIMIT_SUCCESS = "UPDATE_BUDGET_LIMIT_SUCCESS";
export const UPDATE_BUDGET_LIMIT_FAIL = "UPDATE_BUDGET_LIMIT_FAIL";

export const GET_BUDGET_LIMIT_REQUEST = "GET_BUDGET_LIMIT_REQUEST";
export const GET_BUDGET_LIMIT_SUCCESS = "GET_BUDGET_LIMIT_SUCCESS";
export const GET_BUDGET_LIMIT_FAIL = "GET_BUDGET_LIMIT_FAIL";

export const DELETE_BUDGET_LIMIT_REQUEST = "DELETE_BUDGET_LIMIT_REQUEST";
export const DELETE_BUDGET_LIMIT_SUCCESS = "DELETE_BUDGET_LIMIT_SUCCESS";
export const DELETE_BUDGET_LIMIT_FAIL = "DELETE_BUDGET_LIMIT_FAIL";

export const GET_BUDGET_LIMITS_REQUEST = "GET_BUDGET_LIMITS_REQUEST";
export const GET_BUDGET_LIMITS_SUCCESS = "GET_BUDGET_LIMITS_SUCCESS";
export const GET_BUDGET_LIMITS_FAIL = "GET_BUDGET_LIMITS_FAIL";
