export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAIL = "GET_EVENTS_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const ARCHIVE_EVENT_REQUEST = "ARCHIVE_EVENT_REQUEST";
export const ARCHIVE_EVENT_SUCCESS = "ARCHIVE_EVENT_SUCCESS";
export const ARCHIVE_EVENT_FAIL = "ARCHIVE_EVENT_FAIL";
