export const ADD_SAVING_REQUEST = "ADD_SAVING_REQUEST";
export const ADD_SAVING_SUCCESS = "ADD_SAVING_SUCCESS";
export const ADD_SAVING_FAIL = "ADD_SAVING_FAIL";

export const GET_SAVING_BY_MONTH_AND_YEAR_REQUEST =
  "GET_SAVING_BY_MONTH_AND_YEAR_REQUEST";
export const GET_SAVING_BY_MONTH_AND_YEAR_SUCCESS =
  "GET_SAVING_BY_MONTH_AND_YEAR_SUCCESS";
export const GET_SAVING_BY_MONTH_AND_YEAR_FAIL =
  "GET_SAVING_BY_MONTH_AND_YEAR_FAIL";

export const UPDATE_SAVING_REQUEST = "UPDATE_SAVING_REQUEST";
export const UPDATE_SAVING_SUCCESS = "UPDATE_SAVING_SUCCESS";
export const UPDATE_SAVING_FAIL = "UPDATE_SAVING_FAIL";

export const DELETE_SAVING_REQUEST = "DELETE_SAVING_REQUEST";
export const DELETE_SAVING_SUCCESS = "DELETE_SAVING_SUCCESS";
export const DELETE_SAVING_FAIL = "DELETE_SAVING_FAIL";

export const GET_SAVINGS_REQUEST = "GET_SAVINGS_REQUEST";
export const GET_SAVINGS_SUCCESS = "GET_SAVINGS_SUCCESS";
export const GET_SAVINGS_FAIL = "GET_SAVINGS_FAIL";
